# Generated by Django 4.2.6 on 2024-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_reference', models.CharField(max_length=10)),
                ('Period', models.DateField()),
                ('Data_value', models.IntegerField()),
                ('Suppressed', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(max_length=50)),
                ('Units', models.CharField(max_length=50)),
                ('Magnitude', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
                ('Series_title_1', models.CharField(max_length=100)),
                ('Series_title_2', models.CharField(max_length=100)),
                ('Series_title_3', models.CharField(max_length=100)),
            ],
        ),
    ]
