# Generated by Django 4.2.6 on 2024-02-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_business_data_value_alter_business_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Data_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
